### ISSUE TITLE
"glovered.pickle" model

### ISSUE THREAD

**Issue by ayrtondenner** [shivashankarrs/Petitions#1]
Hello. I'm trying to replicate the results of the paper, and I want to know which file should I refer in the "glovered.pickle" code (CNN_ord_elu_MT.py, line 245). Thanks!

**Comment by shivashankarrs** [comment]
Hi, thanks for checking the code. I used http://nlp.stanford.edu/data/glove.840B.300d.zip, the pickle is just reduced to the vocabulary of the dataset.

**Comment by ayrtondenner** [comment]
So, the "glovered.pickle" is the glove.840B.300d.txt, or do I have to do some processing in it? Trying to work directly with this txt file got me a `_pickle.UnpicklingError: invalid load key, ','.` error.

**Comment by ayrtondenner** [comment]
Anyway, I did the following: tried to convert the txt to a pickle file, using the following code:

```
model_txt = open(modelname, 'r', encoding='utf-8')
obj = [model_txt.read()]
with open(picklename, 'wb') as pickle_file:
    pickle.dump(obj, pickle_file, protocol=pickle.HIGHEST_PROTOCOL)
```

With that, I converted the txt file to a pickle file, and then used the code to read the pickle back and went forward with the execution of the code. But later on, you read again the "USPetitions_7K.csv" file (which I suppose it's the "WTP_dataset_1K.csv" file), but it seems the code is trying to read a 'text' property (through `train['text']  = train['text'].str.lower()`, for instance), but neither WTP_dataset_1K.csv nor UK_Petitions_10K.csv has a 'text' column. Is this the right instruction?

**Comment by ayrtondenner** [comment]
Also, where do I find the 'trainscustomwtp'/'valscustomwtp'/'testscustomwtp' custom features text files?

**Comment by shivashankarrs** [comment]
For getting glove pickle, see if this code snippet helps. modelname is the glove embeddings input. vocab is the set of words we want to reduce it to.

```
embeddings = {}

lines = [line.strip().decode("utf-8") for line in open(modelname)]
for line in lines:
    row = line.split(" ")
    if row[0] in vocab:
        embeddings[row[0]] = [float(n) for n in row[1:]]

import pickle
with open(r"glovered.pickle", "wb") as output_file:
    pickle.dump(embeddings, output_file)

```

And, about the custom features, it must be created using the codes given in Python notebook.

**Comment by ayrtondenner** [comment]
I see, but do I have to run a specific notebook to generate the custom features? Sorry, it didn't get clear for me which notebook should I run, I even tried to find the -customwtp suffix, but none notebook has any code having this name.

**Comment by tintuchippy** [comment]
sir, I am doing this paper as part of my final project in M.Tech curriculam
but i have doubt in which Is "USPetitions_7K.csv" is same as "WTP_dataset_1K.csv" pls verify..
if in case of "WTP_dataset_1K.csv" what is "text" column indicate in code train['text'] = train['text'].str.lower() pls verify that.
