### ISSUE TITLE
Opening "WTP_dataset_1K.csv" via notebook

### ISSUE THREAD

**Issue by ayrtondenner** [shivashankarrs/Petitions#2]
I'm trying to open "WTP_dataset_1K.csv" file via Freshness_Title_Features notebook, but when I try to run this code
`petitions = pd.read_csv("WTP_dataset_1K.csv", header=0)`
I get the following error:
`ParserError: Error tokenizing data. C error: Expected 3 fields in line 13, saw 6`

The line referred in this error has the following content

![image](https://user-images.githubusercontent.com/13112588/41435281-b3e56134-6ff4-11e8-97cd-b5e387ca621b.png)

If I try to run the same code with UK_Petitions_10K csv, the reader goes ok, but the next code won't work as  this csv doesn't have neither 'title' or 'content' tags. So, it seems that WTP_dataset_1K has a format problem, right?

**Comment by shivashankarrs** [comment]
Thanks, please check the new file.

**Comment by ayrtondenner** [comment]
That's weird. With the new file, I'm getting this error now:

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 172: invalid start byte`

Edit: I tried with 'ISO-8859-1' encoding, and it worked: it created a DataFrame with a lenght of 1023. Could you updated the read_csv method with parameter `encoding='ISO-8859-1'` ?

**Comment by ayrtondenner** [comment]
I tried with 'ISO-8859-1' encoding, and it worked: it created a DataFrame with a lenght of 1023. Could you updated the read_csv method with parameter `encoding='ISO-8859-1'` ?

**Comment by ayrtondenner** [comment]
Also, where do I find files like 'Petitionstitle' and the others?

**Comment by ayrtondenner** [comment]
Also, I should replace the 'Petitionstitle' call with 'Noaction_title.csv' file, right? It gives me the error `UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 4998: character maps to <undefined>`

I also got a problem with the "decode("utf-8")", but it seems that it is a problem with Python 3, removing it fixes the problem for me, as it seems that you use Python 2.

Edit: the error seems to happen when Python is trying to read line 504 ('action against people who report a false domestic crime for immigration purposes').

Edit 2: once again it was an encoding problem. Updating it with `encoding='utf-8` solved the issue.

**Comment by ayrtondenner** [comment]
Another doubt: where do I find the "NoactionTitle_embeddings" file? I managed to save the "Titleembeddings" file successfully, but I couldn't find the former embedding file.

**Comment by shivashankarrs** [comment]
It must be created using https://github.com/facebookresearch/InferSent
